version: 2.1
jobs:
  test:
    machine:
      image: ubuntu-2004:202101-01
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-v1-{{ checksum "package-lock.json" }}
      - run:
          name: Install node@14.18.0, npm and yarn
          command: |
            set +e
            curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.1/install.sh | bash
            export NVM_DIR="/opt/circleci/.nvm"
            [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
            nvm install v14.18.0
            nvm use v14.18.0
            npm install --global yarn

            echo 'export NVM_DIR="/opt/circleci/.nvm"' >> $BASH_ENV
            echo "[ -s \"$NVM_DIR/nvm.sh\" ] && . \"$NVM_DIR/nvm.sh\"" >> $BASH_ENV
            echo 'nvm use v14.18.0' >> $BASH_ENV
      - run:
          name: npm install
          command: npm install
      - run:
          name: npm install -g firebase-tools
          command: npm install -g firebase-tools
      - run:
          name: Enable extension dev
          command: firebase --open-sesame extdev
      - save_cache:
          key: dependency-cache-v1-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules
      - restore_cache:
          key: dependency-cache-v1-functions-{{ checksum "functions/package-lock.json" }}
      - run:
          name: npm install inside functions
          command: cd functions && npm install
      - save_cache:
          key: dependency-cache-v1-functions-{{ checksum "functions/package-lock.json" }}
          paths:
            - ./functions/node_modules
      - run:
          name: npm run test:ci
          command: npm run test:ci
          environment:
            JEST_JUNIT_OUTPUT_DIR: "reports/junit/js-test-results.xml"
      - store_test_results:
          path: reports/junit
      - store_artifacts:
          path: reports/junit

workflows:
  integration_tests:
    jobs:
      - test
